### ISSUE TITLE
신규 개발기능

### ISSUE THREAD

**Issue by karlkwon** [singleheart/wordchain#2]
Phase-1:
점수:
- ~~게임 시작시 100점을 준다.~~
- ~~정답 제출시 (10)~~
- ~~오답 제출시 penalty 부여 (엄한단어:-10, history에 있는 단어 -5)~~
- 게임 수행중 참가자 전원의 점수 표시.

종료:
- ~~더이상 사전에서 맞는 단어가 없으면 게임 종료~~
- ~~이어질 단어가 사전에 있지만 history에 있으면 종료~~
- ~~한명만 '0'점이 아닌경우 종료~~
- ~~종료 후 새 게임 시작~~
- ~~사용자중 점수가 '0'점 이하인 경우 해당 사용자 observer mode로 변경~~

승리:
- 혼자 참여한 상태에서 종료조건을 만족한 경우 승리로 인정 안함.

Phase-2:
명예의 전당 추가.
접속자 명단.
sign up

Phase-3:
game session 관리
hint 기능?
첫번째 단어로 끝말을 이을 수 없는 경우가 들어온 경우

**Comment by karma822** [comment]
종료 조건 중 "한명만 '0'점이 아닌경우 종료"로 인하여 혼자 플레이가 불가능 하기 때문에
승리: 조건이 발생할 수 없습니다.
