### ISSUE TITLE
Animation(script loading 확인)

### ISSUE THREAD

**Issue by karlkwon** [singleheart/wordchain#6]
권준호C의 기존 c9 에서는 정상 동작하지만 git 에서 새로 down 받은 code는 동작 안됨.
=> 차이점 분석을 하니 https page로 진입하는 경우 animation을 위한 js library loading이 실패한 것임.
=> 현재 이유는 정확히 알 수 없으나 새로 뜨는 창의 주소가 https 인지 아닌지에 따라 이슈 발생.
=> 현재 js library를 down 받아서 Django의 static folder에 넣으면 해결이 될것으로 생각됨.
=> js library의 주소를 https로 시작하게 하는 것 만드로도 문제 해결됨. (이유선J)

**Comment by karma822** [comment]
Fixed by following commit
https://github.com/singleheart/wordchain/commit/d194349349f28172c4f3728e734f4ac44deba92b
